"""Sample data for initializing the Lost and Found app"""

sample_items = [
    {
        'id': '1',
        'title': 'Blue Backpack',
        'description': 'A blue JanSport backpack with laptop compartment. Contains some textbooks.',
        'category': 'Bags',
        'location': 'Library - 2nd Floor',
        'date': '2025-01-28',
        'status': 'active',
        'type': 'found',
        'image': '',
        'imageHash': None,
        'contactName': 'Sarah Johnson',
        'contactInfo': 'sarah.j@campus.edu',
        'createdAt': '2025-01-28T14:30:00',
    },
    {
        'id': '2',
        'title': 'iPhone 14 Pro',
        'description': 'Black iPhone with a cracked screen protector. Has a purple case.',
        'category': 'Electronics',
        'location': 'Student Center',
        'date': '2025-01-29',
        'status': 'active',
        'type': 'lost',
        'image': '',
        'imageHash': None,
        'contactName': 'Mike Chen',
        'contactInfo': 'mike.chen@campus.edu',
        'createdAt': '2025-01-29T09:15:00',
    },
    {
        'id': '3',
        'title': 'Red Water Bottle',
        'description': 'Hydro Flask water bottle, 32oz, with stickers on it.',
        'category': 'Personal Items',
        'location': 'Gym',
        'date': '2025-01-27',
        'status': 'claimed',
        'type': 'found',
        'image': '',
        'imageHash': None,
        'contactName': 'Emma Davis',
        'contactInfo': 'emma.d@campus.edu',
        'createdAt': '2025-01-27T16:45:00',
    },
    {
        'id': '4',
        'title': 'Laptop Charger',
        'description': 'MacBook Pro charger (USB-C), 61W. Left in study room.',
        'category': 'Electronics',
        'location': 'Engineering Building - Room 301',
        'date': '2025-01-30',
        'status': 'active',
        'type': 'found',
        'image': '',
        'imageHash': None,
        'contactName': 'Alex Thompson',
        'contactInfo': 'alex.t@campus.edu',
        'createdAt': '2025-01-30T11:20:00',
    },
    {
        'id': '5',
        'title': 'Silver Watch',
        'description': 'Citizen watch with leather strap. Has sentimental value.',
        'category': 'Accessories',
        'location': 'Cafeteria',
        'date': '2025-01-26',
        'status': 'active',
        'type': 'lost',
        'image': '',
        'imageHash': None,
        'contactName': 'Jordan Lee',
        'contactInfo': 'jordan.lee@campus.edu',
        'createdAt': '2025-01-26T13:00:00',
    },
]

