import { Item } from '../types';

export const mockItems: Item[] = [
  {
    id: '1',
    title: 'Blue Backpack',
    description: 'A blue JanSport backpack with laptop compartment. Contains some textbooks.',
    category: 'Bags',
    location: 'Library - 2nd Floor',
    date: '2025-10-28',
    status: 'active',
    type: 'found',
    contactName: 'Sarah Johnson',
    contactInfo: 'sarah.j@campus.edu',
    createdAt: '2025-10-28T14:30:00',
  },
  {
    id: '2',
    title: 'iPhone 14 Pro',
    description: 'Black iPhone with a cracked screen protector. Has a purple case.',
    category: 'Electronics',
    location: 'Student Center',
    date: '2025-10-29',
    status: 'active',
    type: 'lost',
    contactName: 'Mike Chen',
    contactInfo: 'mike.chen@campus.edu',
    createdAt: '2025-10-29T09:15:00',
  },
  {
    id: '3',
    title: 'Red Water Bottle',
    description: 'Hydro Flask water bottle, 32oz, with stickers on it.',
    category: 'Personal Items',
    location: 'Gym',
    date: '2025-10-27',
    status: 'claimed',
    type: 'found',
    contactName: 'Emma Davis',
    contactInfo: 'emma.d@campus.edu',
    createdAt: '2025-10-27T16:45:00',
  },
  {
    id: '4',
    title: 'Laptop Charger',
    description: 'MacBook Pro charger (USB-C), 61W. Left in study room.',
    category: 'Electronics',
    location: 'Engineering Building - Room 301',
    date: '2025-10-30',
    status: 'active',
    type: 'found',
    contactName: 'Alex Thompson',
    contactInfo: 'alex.t@campus.edu',
    createdAt: '2025-10-30T11:20:00',
  },
  {
    id: '5',
    title: 'Silver Watch',
    description: 'Citizen watch with leather strap. Has sentimental value.',
    category: 'Accessories',
    location: 'Cafeteria',
    date: '2025-10-26',
    status: 'active',
    type: 'lost',
    contactName: 'Jordan Lee',
    contactInfo: 'jordan.lee@campus.edu',
    createdAt: '2025-10-26T13:00:00',
  },
  {
    id: '6',
    title: 'Student ID Card',
    description: 'Student ID for John Smith, class of 2026.',
    category: 'Documents',
    location: 'Parking Lot B',
    date: '2025-10-31',
    status: 'active',
    type: 'found',
    contactName: 'Campus Security',
    contactInfo: 'security@campus.edu',
    createdAt: '2025-10-31T08:30:00',
  },
  {
    id: '7',
    title: 'Textbook: Calculus III',
    description: 'Calculus III textbook with notes inside. Name written on first page.',
    category: 'Books',
    location: 'Math Building - Room 105',
    date: '2025-10-25',
    status: 'pending',
    type: 'found',
    contactName: 'Lisa Wang',
    contactInfo: 'lisa.w@campus.edu',
    createdAt: '2025-10-25T15:10:00',
  },
  {
    id: '8',
    title: 'Black Umbrella',
    description: 'Automatic open/close black umbrella. Lost near main entrance.',
    category: 'Personal Items',
    location: 'Main Building Entrance',
    date: '2025-10-29',
    status: 'active',
    type: 'lost',
    contactName: 'David Park',
    contactInfo: 'david.p@campus.edu',
    createdAt: '2025-10-29T17:40:00',
  },
];

export const categories = [
  'All',
  'Electronics',
  'Bags',
  'Books',
  'Documents',
  'Accessories',
  'Personal Items',
  'Keys',
  'Clothing',
  'Other',
];

export const locations = [
  'All',
  'Library - 2nd Floor',
  'Library - 3rd Floor',
  'Student Center',
  'Gym',
  'Cafeteria',
  'Engineering Building - Room 301',
  'Math Building - Room 105',
  'Main Building Entrance',
  'Parking Lot B',
  'Dorms',
  'Other',
];
